env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    
task:
    name: recovery
    timeout_in: 120m
    container:
      image: brock5555/recovery
      cpu: 7
      memory: 8G
    build_script:
      - bash build.sh #trial-1
    
